# Generated by Django 3.2.4 on 2021-07-02 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='transport',
        ),
        migrations.AddField(
            model_name='event',
            name='transport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.transport'),
        ),
    ]
